=== johentsch/bopp/schemas/v1/annotation.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "v1/annotation.json",
  "title": "Annotation",
  "type": "object",
  "properties": {
    "object_type": {
      "const": "annotation"
    },
    "media_id": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9]+:.*$"
    },
    "bopp_version": {
      "type": "string",
      "pattern": "^1\\.\\d+\\.\\d+$",
      "description": "The Semantic Version of the BOPP schema (e.g., 1.0.0)"
    },
    "metadata": {
      "description": "The metadata describing the annotation",
      "$ref": "metadata.json"
    },
    "extent": {
      "description": "The parallel array of time/space boundaries (e.g., time_interval, point)",
      "$ref": "extents.json"
    },
    "payload": {
      "description": "The parallel array of values (e.g., beat, chord)",
      "$ref": "payloads.json"
    },
    "confidence": {
      "description": "Optional parallel array of likelihoods or votes",
      "$ref": "confidences.json"
    }
  },
  "required": [
    "media_id",
    "payload"
  ],
  "description": "A single timeline of observations: one extent + one payload (+ optional confidence) as parallel columnar arrays."
}

=== johentsch/bopp/dlc_example_harmony.bopp.json
{"media_id":"dlc:ABC/n01op18-1_01","payload":{"payload_type":"dcml_harmony","label":["F.I","V","I","IV6","V65","I","vi","ii6","V(64)","V\\\\","I","V","I","IV6","#viio7(6)/vi","#viio7/vi","#viio7(4)/ii","#viio7/ii","ii6(11#7b6)","ii6","V(64)","V(6)","V7","I\\\\","I","viio7(b4)/V","viio7/V","V7(4)","V7","V7(4)/IV","V7/IV","ii6(9#4)","ii6","V7","I\\\\","V[I6","V64","V43","I6(6)","I6","V2(6)","V2","V2]","V65/vi","vi","V65/V","v.i","VI","V43/VI","VI6(6)","VI6","viio65/VII","#viio65","i6","iio6","viio7/V","V","V(64)","V","V(64)","V","V(64)","V","V(64)","V","i","V","V\\\\","V.V","@none","ii","V","V2","I6","viio6","I","viio(64)","viio","@none","viio","V65/vi","viio64/vi","vi6","vi","V7/V","V(94)","V\\\\","@none","ii","V","V65","I","V43","I6","viio43(2)","viio43\\\\","@none","viio7","i","viio7/V","V(b64)","V7","I\\\\","I","V43","#viio65/ii","viio","ii6","V","V7","I\\\\","I6","V64","viio","I","IV","I6","viio6","viio","I","V65/V","V(64)","V7","I\\\\","I6","viio6","viio","I","IV","I6","viio6","viio","i","bVI","viio7/V","Ger6/vi","vi64","ii","V7","I[I64","V7","I64","V7","I64","I]","I","I\\\\","III.I","IV.I","I64","IV64","IV6","viio","I","vi.#viio","#viio7","#viio65","#viio7","i","#viio65","i6","#viio43","i6","#viio43","i6","@none","ii.#viio2","@none","#viio7","VI6","V65/ii","#viio65","i6","#viio43","i6","#viio43","i6","@none","v.#viio2","@none","V2/ii","#viio7","VI6","#viio/ii","V43","iio6","VIM43","#viio65","i6","#viio65","i6","i.#viio43","i6","#viio43","i6","iv.viio43","i6","viio43","i6","i","VI","i6","i","VI","i64","V65/V","i.i","i6","VI","i6","i","VI","i64","viio7/V","I.V","V6","V64","V","V7","V","V7","V","V7","V","I","V","I","IV6","V65","I","vi","ii6","V(64)","V\\\\","@none","I6","bVI.vi","IV","ii","V(64)","V","I\\\\","vi","ii6","V(64)","V","vi","IV","ii","V(64)/vi","V/vi","vi","IV","ii","I6","V7/IV","bII.I","I","V43","I6(6)","I6","V6(6)","V6","V7","I(#2)","I","i.iv64","V65","i","v6","Ger6","V","i","V","i","V","i","V","i","V","i","V","V\\\\","I.V","@none","ii","V","V2","I6","V64","I","viio(64)","viio","@none","viio","V.V6/ii","V2/ii","ii6","ii","V","I(94)","I\\\\","@none","I.ii","V","V65","I","viio6","I6","viio43(2)","viio43","@none","viio7","i","viio7/V","V(b64)","V7","I\\\\","I","V43","#viio6/ii","#viio65/ii","ii6","ii","V","V7","I\\\\","V64","V65","I","IV","I6","viio6","viio","I","IV","V(64)","V7","I\\\\","viio6","viio","I","IV","I6","viio6","viio","i","VI","viio7/V","Ger6/vi","V(64)/vi","ii","V7","I\\\\","I[I6","V2","I6","I64","V7","I64","I64]","I","IV","bVII","V/ii","ii","V","V7/V","iii","V6/V","V","IV6","viio","V43/V","V65/V","V7/V","V7","I","V2","V65","V[V7","I64","V7","V7]","#viio7/vi","vi","#viio65/vi","#viio7/ii","ii","viio7/IV","viio7/V","V(64)","V7","I\\\\","I[I","It6","I64","iv6","I64","iv","I","Fr6","I]","I","I\\\\"],"globalkey":["F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F","F"],"localkey":["I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","v","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","V","III","IV","IV","IV","IV","IV","IV","vi","vi","vi","vi","vi","vi","vi","vi","vi","vi","vi","vi","ii","ii","ii","ii","ii","ii","ii","ii","ii","ii","ii","ii","v","v","v","v","v","v","v","v","v","v","v","v","v","i","i","i","i","iv","iv","iv","iv","iv","iv","iv","iv","iv","iv","iv","i","i","i","i","i","i","i","i","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bVI","bII","bII","bII","bII","bII","bII","bII","bII","bII","bII","i","i","i","i","i","i","i","i","i","i","i","i","i","i","i","i","i","I","I","I","I","I","I","I","I","I","I","I","I","V","V","V","V","V","V","V","V","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I","I"],"pedal":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"V","V","V","V","V","V","V","V",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"I","I","I","I","I","I",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"I","I","I","I","I","I","I",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,"V","V","V","V",null,null,null,null,null,null,null,null,null,null,"I","I","I","I","I","I","I","I","I",null,null],"chord":["I","V","I","IV6","V65","I","vi","ii6","V(64)","V","I","V","I","IV6","#viio7(6)/vi","#viio7/vi","#viio7(4)/ii","#viio7/ii","ii6(11#7b6)","ii6","V(64)","V(6)","V7","I","I","viio7(b4)/V","viio7/V","V7(4)","V7","V7(4)/IV","V7/IV","ii6(9#4)","ii6","V7","I","I6","V64","V43","I6(6)","I6","V2(6)","V2","V2","V65/vi","vi","V65/V","i","VI","V43/VI","VI6(6)","VI6","viio65/VII","#viio65","i6","iio6","viio7/V","V","V(64)","V","V(64)","V","V(64)","V","V(64)","V","i","V","V","V","@none","ii","V","V2","I6","viio6","I","viio(64)","viio","@none","viio","V65/vi","viio64/vi","vi6","vi","V7/V","V(94)","V","@none","ii","V","V65","I","V43","I6","viio43(2)","viio43","@none","viio7","i","viio7/V","V(b64)","V7","I","I","V43","#viio65/ii","viio","ii6","V","V7","I","I6","V64","viio","I","IV","I6","viio6","viio","I","V65/V","V(64)","V7","I","I6","viio6","viio","I","IV","I6","viio6","viio","i","bVI","viio7/V","Ger6/vi","vi64","ii","V7","I64","V7","I64","V7","I64","I","I","I","I","I","I64","IV64","IV6","viio","I","#viio","#viio7","#viio65","#viio7","i","#viio65","i6","#viio43","i6","#viio43","i6","@none","#viio2","@none","#viio7","VI6","V65/ii","#viio65","i6","#viio43","i6","#viio43","i6","@none","#viio2","@none","V2/ii","#viio7","VI6","#viio/ii","V43","iio6","VIM43","#viio65","i6","#viio65","i6","#viio43","i6","#viio43","i6","viio43","i6","viio43","i6","i","VI","i6","i","VI","i64","V65/V","i","i6","VI","i6","i","VI","i64","viio7/V","V","V6","V64","V","V7","V","V7","V","V7","V","I","V","I","IV6","V65","I","vi","ii6","V(64)","V","@none","I6","vi","IV","ii","V(64)","V","I","vi","ii6","V(64)","V","vi","IV","ii","V(64)/vi","V/vi","vi","IV","ii","I6","V7/IV","I","I","V43","I6(6)","I6","V6(6)","V6","V7","I(#2)","I","iv64","V65","i","v6","Ger6","V","i","V","i","V","i","V","i","V","i","V","V","V","@none","ii","V","V2","I6","V64","I","viio(64)","viio","@n
